### PR TITLE
remove click version dependency

### PR DESCRIPTION
**Pull request by ronif**
Hey @ocefpaf

I removed the constraint on `click` in the recipe. It doesn't exist upstream and a quick test I ran seems to work.

Thanks

### CODE REVIEW

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by josiasritter** [comment]
Hi @ocefpaf,

When installing elevation via conda-forge, the click constraint still seems to be in place, which creates conflicts with other packages requiring click versions >= 7 .
Furthermore, it seems that the default installation via conda-forge ("conda install -c conda-forge elevation") installs version 1.0.6 instead of the most recent version 1.1.3. But anyways, the click constraint is also in place when specifying the most recent version ("conda install -c conda-forge elevation=1.1.3").

Could this be updated?

Many thanks,

Josias

**Comment by ocefpaf** [comment]
https://github.com/conda-forge/elevation-feedstock/pull/8 should fix that.

**Comment by josiasritter** [comment]
Yes, now it works. Thanks for the quick fix!

**Pull request merged**
